api.key=1705d2b7ecmshf032025857d18e7p1fd943jsnf0cde94005ad
persistence.type=DEMO
demo.athlete=""
demo.password=""
db.url=jdbc:mysql://localhost:3306/fitconnect
db.user=francesco
db.password=Trimone38
ui.type=cli